language: c
sudo: false

os:
    - osx
    - linux

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1  LUANUMBER=double
    - LUA=lua5.2  LUANUMBER=double
    - LUA=lua5.3  LUANUMBER=double
    - LUA=luajit     # latest stable version (2.0.x)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

  # 'bleeding edge' LuaJIT may fail without breaking the build
matrix:
  # 'bleeding edge' LuaJIT may fail without breaking the build
  allow_failures:
    - env: LUA=luajit2.0
    - env: LUA=luajit2.1

cache:
  directories:
    - $HOME/install

before_install:
  - source .travis/setenv_lua.sh
  - source .travis/setup_compressor_decompressor.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-utils; fi

script:
  - luacheck -g -u .
  #- lua -v -lluacov tests/LibDeflateTest.lua --shuffle
  # converage test makes it too slow.
  - lua tests/LibDeflateTest.lua --verbose --shuffle

after_success:
  # - luacov-coveralls -v --include %./LibDeflate.lua
  # converage test is a good thing, but not for this project.

notifications:
  email:
    on_success: never
    on_failure: always
