language: c
sudo: false

os:
    - osx
    - linux

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1.4  LUANUMBER=double
    - LUA=luajit     # latest stable version (2.0.x)
    - LUA=lua5.1.5  LUANUMBER=double
    - LUA=lua5.2.4  LUANUMBER=double
    - LUA=lua5.3.3  LUANUMBER=double
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

matrix:
  # 'bleeding edge' LuaJIT may fail without breaking the build
  allow_failures:
    - env: LUA=luajit2.0
    - env: LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh
  - source .travis/setup_compressor_decompressor.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-utils; fi

script:
  - luacheck -g -u .
  - lua tests/LibDeflateTest.lua --verbose --shuffle
  # converage test makes it too slow. so only run once in luajit linux
  # Don't shuffle coverage test so we see progress
  - if [[ "$LUA" == "luajit" && "$TRAVIS_OS_NAME" == "linux" ]]; then lua -lluacov tests/LibDeflateTest.lua CodeCoverage --verbose; fi

after_success:
  - if [[ "$LUA" == "luajit" && "$TRAVIS_OS_NAME" == "linux" ]]; then luacov-coveralls -v --include %./LibDeflate.lua; fi

notifications:
  email:
    on_success: never
    on_failure: always
