language: c
sudo: false

env:
  global:
    - LUAROCKS=2.2.2

matrix:
    include:
    - env: LUA=luaj3.0.1 NO_EXTENDED_TESTS=1 LESS_BIG_TESTS=1
      jdk: oraclejdk8
      os: linux
    - env: LUA=luaj2.0.3 NO_EXTENDED_TESTS=1 LESS_BIG_TESTS=1
      jdk: oraclejdk8
      os: linux
    - env: LUA=ljx1.3 NO_EXTENDED_TESTS=1
      os: linux
    - env: LUA=lua5.1.4
      os: linux
    - env: LUA=lua5.2.4
      os: linux
    - env: LUA=lua5.3.3
      os: linux
    - env: LUA=luajit2.0.4
      os: linux
    - env: LUA=luajit2.1.0-beta3
      os: linux
    - env: LUA=lua5.1.4
      os: mac
    - env: LUA=lua5.2.4
      os: mac
    - env: LUA=lua5.3.3
      os: mac
    - env: LUA=luajit2.0.4
      os: mac
    - env: LUA=luajit2.1.0-beta3
      os: mac
    allow_failures:
    - env: LUA=luaj3.0.1 NO_EXTENDED_TESTS=1 LESS_BIG_TESTS=1
      jdk: oraclejdk8
      os: linux
    - env: LUA=luaj2.0.3 NO_EXTENDED_TESTS=1 LESS_BIG_TESTS=1
      jdk: oraclejdk8
      os: linux
    - env: LUA=ljx1.3 NO_EXTENDED_TESTS=1
      os: linux
    - env: LUA=luajit2.1.0-beta3
      os: linux
    - env: LUA=luajit2.1.0-beta3
      os: mac

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-utils; fi
  - source .travis/setenv.sh
  - bash .travis/install_lua.sh
  - bash .travis/install_compressor_decompressor.sh
  - bash .travis/install_luarocks_packages.sh

script:
  - if [[ -z "${NO_EXTENDED_TESTS} ]]; then luacheck .; fi
  - if [[ -z "${NO_EXTENDED_TESTS} ]]; then bash tests/dev_scripts/release.sh; fi
  - if [[ -z "${NO_EXTENDED_TESTS} ]]; then cd docs && ldoc . && cd ..; fi
  - lua examples/example.lua
  - lua tests/Test.lua --verbose --shuffle ${NO_EXTENDED_TESTS:+--no-extended-tests} ${LESS_BIG_TESTS:+--less-big-tests}
  # converage test makes it too slow. so only run once in luajit linux
  # Don't shuffle coverage test so we see progress
  - if [[ "$LUA" == "luajit" && "$TRAVIS_OS_NAME" == "linux" ]]; then lua tests/Test.lua CommandLineCodeCoverage --verbose; fi
  - if [[ "$LUA" == "luajit" && "$TRAVIS_OS_NAME" == "linux" ]]; then lua -lluacov tests/Test.lua CodeCoverage --verbose; fi

after_success:
  - if [[ "$LUA" == "luajit" && "$TRAVIS_OS_NAME" == "linux" ]]; then luacov; fi
  - if [[ "$LUA" == "luajit" && "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl --retry 10 --retry-delay 10 -s https://codecov.io/bash); fi

notifications:
  email:
    on_success: change
    on_failure: always