language: c
sudo: false

os:
    - osx
    - linux

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1  LUANUMBER=double
    - LUA=luajit     # latest stable version (2.0.x)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

  # 'bleeding edge' LuaJIT may fail without breaking the build
matrix:
  # 'bleeding edge' LuaJIT may fail without breaking the build
  allow_failures:
    - env: LUA=luajit2.0
    - env: LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh
  - source .travis/setup_compressor_decompressor.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-utils; fi

script:
  - luacheck . -qo 011
  - lua -v -lluacov tests/LibDeflateTest.lua --shuffle

after_success:
  - luacov-coveralls -v --include %./LibDeflate.lua

notifications:
  email:
    on_success: never
    on_failure: always
