language: c
sudo: false

os:
    - osx
    - linux

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1  LUANUMBER=double
    - LUA=lua5.2  LUANUMBER=double
    - LUA=lua5.3  LUANUMBER=double
    - LUA=luajit     # latest stable version (2.0.x)

cache:
  directories:
    - $HOME/install

before_install:
  - source .travis/setenv_lua.sh
  - source .travis/setup_compressor_decompressor.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-utils; fi

script:
  - luacheck . -qo 011
  - lua -v -lluacov tests/LibDeflateTest.lua --shuffle

after_success:
  - luacov-coveralls -v --include %./LibDeflate.lua

notifications:
  email:
    on_success: never
    on_failure: always
